### ISSUE TITLE
Running 'make' at top level does not work

### ISSUE THREAD

**Issue by hackerb9** [BentonEdmondson/libgourou-utils#1]
The main makefile should have a dependency to compile libupdfparser.a in lib/updfparser/, but it doesn't:

```bash
libgourou-utils$ make
mkdir lib
mkdir obj
g++ -Wall -fPIC -I./include -I./lib -I./lib/pugixml/src/ -I./lib/updfparser/include -O2 -c src/libgourou.cpp -o obj/libgourou.o
src/libgourou.cpp:25:10: fatal error: uPDFParser.h: No such file or directory
   25 | #include <uPDFParser.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:51: obj/libgourou.o] Error 1
```

Similarly, the makefile in lib/updfparser should have a dependency to compile all the object files before libupdfparser.a:

```
$ make -C lib/updfparser libupdfparser.a
make: Entering directory 'libgourou-utils/lib/updfparser'
g++ -Wall -fPIC -I./include -O2 -c src/uPDFParser.cpp -o obj/uPDFParser.o
Assembler messages:
Fatal error: can't create obj/uPDFParser.o: No such file or directory
make: *** [Makefile:41: obj/uPDFParser.o] Error 1
make: Leaving directory 'libgourou-utils/lib/updfparser'
```

For now, I'm just working around it by doing running the dependencies by hand:

```
make -C lib/updfparser
make -C lib/updfparser libupdfparser.a
make
```

Oh, and while updating the main makefile, it would be a good idea to change the `clean` target so it deletes the object files created in lib/updfparser. Also, the `ultraclean` target currently deletes the entire lib directory which would be reasonable except that for some reason the updfparser source code is stored in there, so that should definitely needs to be fixed.

**Comment by BentonEdmondson** [comment]
This repo exists for the sole purpose of packaging libgourou with Nix with as few changes as possible. This is stated clearly in the readme. To build it, run `nix build`. If you are not using Nix, this repo is not applicable to you; you should be building the upstream package (http://indefero.soutade.fr/p/libgourou/).

**Comment by hackerb9** [comment]
Thank you. I had not understood that Knock is only for people using Nix. If someone wanted to use knock without Nix is that okay? Or would you encourage them to just write their own frontend to libgourou?

**Comment by BentonEdmondson** [comment]
> I had not understood that Knock is only for people using Nix.

I never said Knock is only for people using Nix. In fact I never even mentioned Knock because you opened an issue about this project, not Knock. *This repository* is libgourou packaged with Nix. If you are not using Nix, this repository is not relevant to you because it only exists to package libgourou with Nix. Again, this is clearly stated in this repository's readme. If you want to use libgourou on a non-Nix system, build it from the location I linked above.

> If someone wanted to use knock without Nix is that okay?

Yes, the instructions to do so are clearly listed in Knock's readme. If you have an issue with Knock, open an issue in that repository, not here. I estimate the vast majority of Knock users are on non-Nix systems.
